packages:
  - .

allowBuilds:
  '@tailwindcss/oxide': true
  core-js: false
  cpu-features: true
  esbuild: false
  osx-temperature-sensor: true
  protobufjs: true
  sharp: true
  ssh2: true

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - osx-temperature-sensor
  - protobufjs
  - sharp
