---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Developer:
    - Semaphore:
        - icon: sh-semaphore-ui.svg
          href: http://{{HOMEPAGE_VAR_SEMAPHORE_URL}}:{{HOMEPAGE_VAR_SEMAPHORE_PORT}}

    - Github:
        - icon: si-github
          href: https://github.com/
    
    - Proxmox Helper Scripts:
        - icon: proxmox.svg
          href: https://helper-scripts.com/
    
    - Cloudflare:
        - icon: cloudflare.svg
          href: https://dash.cloudflare.com/

    - Claude:
        - icon: si-claude
          href: https://claude.ai/

    - IT Tools:
        - icon: it-tools.svg
          href: https://tools.quantumbyte.dev/

    - Homepage:
        - icon: homepage.png
          href: https://gethomepage.dev/

- Productivity:
    - Gmail:
        - icon: gmail.svg
          href: https://gmail.com/

    - Outlook:
        - icon: sh-microsoft-outlook.svg
          href: https://outlook.office.com/mail/
    
- Entertainment:
    - YouTube:
        - icon: si-youtube-#FF0000
          href: https://youtube.com/

    - Twitch:
        - icon: si-twitch-#9146FF
          href: https://www.twitch.tv/

    - Reddit:
        - icon: si-reddit
          href: https://www.reddit.com/

- Torrents/Indexers:
    - DrukenSlug:
        - icon: /icons/ds-icon.png
          href: https://drunkenslug.com/

    - NZB Geek:
        - icon: /icons/nzbgeek-icon.png
          href: https://nzbgeek.info/dashboard.php

    - IPTorrents:
        - abbr: IPT
          href: https://ipt.lol/

- ESN:
    - PWS:
        - href: https://password.internal.esngroup.com.au
    - ProofPoint:
        - abbr: PP
          href: https://us4.proofpointessentials.com/app/login.php
    - Console:
        - icon: adobe.svg
          href: https://adminconsole.adobe.com/r/
    - GoTo Admin:
        - icon: /icons/goto.png
          href: https://admin.goto.com/
    - OKTA:
        - icon: si-okta
          href: https://esngroup-com.okta.com/
    - Swoop:
        - icon: 
          href: https://portal.swoop.com.au/login
    - UniFi:
        - icon: unifi.svg
          href: https://account.ui.com/login

- M365:
    - Admin:
        - icon: microsoft-365.svg
          href: https://admin.cloud.microsoft

- CONNECTWISE:
    - ScreenConnect:
        - icon: screenconnect.svg
          href: https://auth.connectwise.com/Account/Login?ReturnUrl=%2Fconnect%2Fauthorize%2Fcallback%3Fresponse_type%3Dcode%26client_id%3Drmmau-ESNGroup%26redirect_uri%3Dhttps%253A%252F%252Frmmau-esngroup.screenconnect.com%252F__Authentication%252FConnectWiseAsio%252FLogin%26state%3D%252FHost%2523Support%252FAll%252520Sessions%252F%252Fe31b6c13-58ee-4145-ab08-36f9a5c1e56a%252FStart%26scope%3Dopenid%2520profile%2520email

- CYBER:
    - AnyRun:
        - icon:
          href: https://app.any.run/

- DOMAINS/DNS:
    - WHOIS-AU:
        - icon: /icons/whois-au.png
          href: https://whois.auda.org.au/

- OSINT:
    - HaveIBeenPwned:
        - icon: si-haveibeenpwned
          href: https://haveibeenpwned.com/
