---
zues:
  url: https://{{HOMEPAGE_VAR_ZUES_PROX_URL}}:{{HOMEPAGE_VAR_PROXMOX_PORT}}
  token: "{{HOMEPAGE_VAR_PROXMOX_TOKEN}}"
  secret: "{{HOMEPAGE_VAR_PROXMOX_SECRET}}"

mars:
  url: https://{{HOMEPAGE_VAR_MARS_PROX_URL}}:{{HOMEPAGE_VAR_PROXMOX_PORT}}
  token: "{{HOMEPAGE_VAR_PROXMOX_TOKEN}}"
  secret: "{{HOMEPAGE_VAR_PROXMOX_SECRET}}"