---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Info:
    - Media-Info: 
        - Plex:
            icon: plex.svg
            href: http://{{HOMEPAGE_VAR_PLEX_URL}}:{{HOMEPAGE_VAR_PLEX_PORT}}/web
            proxmoxNode: "{{HOMEPAGE_VAR_PROXMOX_NODE_1}}"
            proxmoxVMID: "{{HOMEPAGE_VAR_PLEX_VMID}}"
            proxmoxType: lxc
            widget:
                type: plexrecent
                url: http://{{HOMEPAGE_VAR_PLEX_URL}}:{{HOMEPAGE_VAR_PLEX_PORT}}
                key: "{{HOMEPAGE_VAR_PLEX_TOKEN}}"

        - Upcoming Releases:
            icon: notion-calendar.svg
            widget:
                type: calendar
                view: agenda
                maxEvents: 10
                showTime: true
                timezone: Australia/Perth
                integrations:
                    - type: sonarr
                      service_group: ARR Stack
                      service_name: Sonarr
                      color: teal
                    - type: radarr
                      service_group: ARR Stack
                      service_name: Radarr
                      color: amber
    
    - Dota 2:
        - Dota 2: 
            href: https://www.dota2.com
            widget:
                type: dota2
                key: "{{HOMEPAGE_VAR_PANDASCORE_API_KEY}}"

- ARR Stack:
    - Radarr:
        icon: radarr.svg
        href: http://{{HOMEPAGE_VAR_RADARR_URL}}:{{HOMEPAGE_VAR_RADARR_PORT}}
        proxmoxNode: "{{HOMEPAGE_VAR_PROXMOX_NODE_1}}"
        proxmoxVMID: "{{HOMEPAGE_VAR_RADARR_VMID}}"
        proxmoxType: lxc
        widget:
            type: radarr
            url: http://{{HOMEPAGE_VAR_RADARR_URL}}:{{HOMEPAGE_VAR_RADARR_PORT}}
            key: "{{HOMEPAGE_VAR_RADARR_API_KEY}}"

    - Sonarr:
        icon: sonarr.svg
        href: http://{{HOMEPAGE_VAR_SONARR_URL}}:{{HOMEPAGE_VAR_SONARR_PORT}}
        proxmoxNode: "{{HOMEPAGE_VAR_PROXMOX_NODE_1}}"
        proxmoxVMID: "{{HOMEPAGE_VAR_SONARR_VMID}}"
        proxmoxType: lxc
        widget:
            type: sonarr
            url: http://{{HOMEPAGE_VAR_SONARR_URL}}:{{HOMEPAGE_VAR_SONARR_PORT}}
            key: "{{HOMEPAGE_VAR_SONARR_API_KEY}}"

    - Seerr:
        icon: seerr.svg
        href: http://{{HOMEPAGE_VAR_SEERR_URL}}:{{HOMEPAGE_VAR_SEERR_PORT}}
        proxmoxNode: "{{HOMEPAGE_VAR_PROXMOX_NODE_2}}"
        proxmoxVMID: "{{HOMEPAGE_VAR_SEERR_VMID}}"
        proxmoxType: lxc
        widget:
            type: jellyseerr
            url: http://{{HOMEPAGE_VAR_SEERR_URL}}:{{HOMEPAGE_VAR_SEERR_PORT}}
            key: "{{HOMEPAGE_VAR_SEERR_API_KEY}}"

    - Tautulli:
        icon: tautulli.svg
        href: http://{{HOMEPAGE_VAR_PLEX_URL}}:{{HOMEPAGE_VAR_PLEX_PORT}}
        proxmoxNode: "{{HOMEPAGE_VAR_PROXMOX_NODE_2}}"
        proxmoxVMID: "{{HOMEPAGE_VAR_TAUTULLI_VMID}}"
        proxmoxType: lxc
        widget:
            type: tautulli
            url: http://{{HOMEPAGE_VAR_TAUTULLI_URL}}:{{HOMEPAGE_VAR_TAUTULLI_PORT}}
            key: "{{HOMEPAGE_VAR_TAUTULLI_API_KEY}}"
            enableUser: true
            showEpisodeNumber: true
            expandOneStreamToTwoRows: true

    - Bazarr:
        icon: bazarr.svg
        href: http://{{HOMEPAGE_VAR_BAZARR_URL}}:{{HOMEPAGE_VAR_BAZARR_PORT}}
        proxmoxNode: "{{HOMEPAGE_VAR_PROXMOX_NODE_1}}"
        proxmoxVMID: "{{HOMEPAGE_VAR_SONARR_VMID}}"
        proxmoxType: lxc
        widget:
            type: bazarr
            url: http://{{HOMEPAGE_VAR_BAZARR_URL}}:{{HOMEPAGE_VAR_BAZARR_PORT}}
            key: "{{HOMEPAGE_VAR_BAZARR_API_KEY}}"

# - Servers:
#     - QB Proxmox Cluster:
#         icon: proxmox.svg
#         href: https://{{HOMEPAGE_VAR_ZUES_PROX_URL}}:{{HOMEPAGE_VAR_PROXMOX_PORT}}
#         widget:
#             type: proxmox
#             url: https://{{HOMEPAGE_VAR_ZUES_PROX_URL}}:{{HOMEPAGE_VAR_PROXMOX_PORT}}
#             username: "{{HOMEPAGE_VAR_PROXMOX_TOKEN}}"
#             password: "{{HOMEPAGE_VAR_PROXMOX_SECRET}}"

#     - VPS:
#         icon: sh-univention-corporate-server.svg

- Downloads:
    - QBittorrent:
        icon: qbittorrent.svg
        href: http://{{HOMEPAGE_VAR_QBIT_URL}}:{{HOMEPAGE_VAR_QBIT_PORT}}
        proxmoxNode: "{{HOMEPAGE_VAR_PROXMOX_NODE_1}}"
        proxmoxVMID: "{{HOMEPAGE_VAR_QBIT_VMID}}"
        proxmoxType: lxc
        widget:
            type: qbittorrent
            url: http://{{HOMEPAGE_VAR_QBIT_URL}}:{{HOMEPAGE_VAR_QBIT_PORT}}
            username: "{{HOMEPAGE_VAR_QBIT_USER}}"
            password: "{{HOMEPAGE_VAR_QBIT_PASSWORD}}"

    - SABnzbd:
        icon: sabnzbd.svg
        href: http://{{HOMEPAGE_VAR_SABZNDB_URL}}:{{HOMEPAGE_VAR_SABZNDB_PORT}}
        proxmoxNode: "{{HOMEPAGE_VAR_PROXMOX_NODE_1}}"
        proxmoxVMID: "{{HOMEPAGE_VAR_SABZNDB_VMID}}"
        proxmoxType: lxc
        widget:
            type: sabnzbd
            url: http://{{HOMEPAGE_VAR_SABZNDB_URL}}:{{HOMEPAGE_VAR_SABZNDB_PORT}}
            key: "{{HOMEPAGE_VAR_SABZNDB_API_KEY}}"

- Network:
    - Speedtest Tracker:
        icon: speedtest-tracker.png
        href: http://{{HOMEPAGE_VAR_SPEEDTEST_URL}}:{{HOMEPAGE_VAR_SPEEDTEST_PORT}}
        proxmoxNode: "{{HOMEPAGE_VAR_PROXMOX_NODE_2}}"
        proxmoxVMID: "{{HOMEPAGE_VAR_SPEEDTEST_VMID}}"
        proxmoxType: lxc
        widget:
            type: speedtest
            url: http://{{HOMEPAGE_VAR_SPEEDTEST_URL}}:{{HOMEPAGE_VAR_SPEEDTEST_PORT}}
            version: 2
            key: "{{HOMEPAGE_VAR_SPEEDTEST_API_KEY}}"

    - Traefik:
        icon: traefik.svg
        href: http://{{HOMEPAGE_VAR_TRAEFIK_URL}}:{{HOMEPAGE_VAR_TRAEFIK_PORT}}
        proxmoxNode: "{{HOMEPAGE_VAR_PROXMOX_NODE_1}}"
        proxmoxVMID: "{{HOMEPAGE_VAR_TRAEFIK_VMID}}"
        proxmoxType: lxc
        # widget:
        #     type: traefik
        #     url: http://{{HOMEPAGE_VAR_TRAEFIK_URL}}:{{HOMEPAGE_VAR_TRAEFIK_PORT}}
        #     username: "{{HOMEPAGE_VAR_TRAEFIK_USER}}"
        #     password: "{{HOMEPAGE_VAR_TRAEFIK_PASSWORD}}"

    - UniFi:
        icon: unifi.svg
        href: http://{{HOMEPAGE_VAR_UNIFI_URL}}:{{HOMEPAGE_VAR_UNIFI_PORT}}
        proxmoxNode: "{{HOMEPAGE_VAR_PROXMOX_NODE_1}}"
        proxmoxVMID: "{{HOMEPAGE_VAR_UNIFI_VMID}}"
        proxmoxType: lxc
        # widget:
        #     type: unifi
        #     url: https://{{HOMEPAGE_VAR_UNIFI_URL}}:{{HOMEPAGE_VAR_UNIFI_PORT}}
        #     site: Site Name
        #     key: "{{HOMEPAGE_VAR_UNIFI_API_KEY}}"

#     - EdgeSwitch:
#         icon: ubiquiti.svg
#         href: https://{{HOMEPAGE_VAR_SWITCH_URL}}:{{HOMEPAGE_VAR_SWITCH_PORT}}

- Monitoring:
    - Pulse:
        icon: pulse.svg
        href: http://{{HOMEPAGE_VAR_PULSE_URL}}:{{HOMEPAGE_VAR_PULSE_PORT}}
        proxmoxNode: "{{HOMEPAGE_VAR_PROXMOX_NODE_1}}"
        proxmoxVMID: "{{HOMEPAGE_VAR_PULSE_VMID}}"
        proxmoxType: lxc

    - Patchmon:
        icon: patchmon.svg
        href: http://{{HOMEPAGE_VAR_PATCHMON_URL}}:{{HOMEPAGE_VAR_PATCHMON_PORT}}
        proxmoxNode: "{{HOMEPAGE_VAR_PROXMOX_NODE_2}}"
        proxmoxVMID: "{{HOMEPAGE_VAR_PATCHMON_VMID}}"
        proxmoxType: lxc

    - Domain Monitor:
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/domain-monitor.png
        href: http://{{HOMEPAGE_VAR_DOMAINS_URL}}:{{HOMEPAGE_VAR_DOMAINS_PORT}}
        proxmoxNode: "{{HOMEPAGE_VAR_PROXMOX_NODE_1}}"
        proxmoxVMID: "{{HOMEPAGE_VAR_DOMAINS_VMID}}"
        proxmoxType: lxc

# - Security:
#     - OPNsense:
#         icon: opnsense.svg
#         href: http://{{HOMEPAGE_VAR_OPNSENSE_URL}}:{{HOMEPAGE_VAR_OPNSENSE_PORT}}

#     - Crowdsec:
#         icon: crowdsec.svg
#         href: https://app.crowdsec.net/

    - Wazuh:
        icon: wazuh.svg
        href: https://{{HOMEPAGE_VAR_WAZUH_URL}}:{{HOMEPAGE_VAR_WAZUH_PORT}}
        proxmoxNode: "{{HOMEPAGE_VAR_PROXMOX_NODE_1}}"
        proxmoxVMID: "{{HOMEPAGE_VAR_WAZUH_VMID}}"
        proxmoxType: lxc